### ISSUE TITLE
Soft reset on arduino through bluesmirf

### ISSUE THREAD

**Issue by msoula** [sparkfun/BlueSMiRF#6]
Hi,
I would like to soft reset my arduino via the bluesmirf silver device. Would that be possible ?

**Comment by bboyho** [comment]
Hi,

This sounds more like a technical support related question instead of an issue with the product. However, here are some of my thoughts on approaching this:

Theoretically, it may be possible but I have not tried this method before. I would assume that you send a serial character wirelessly to the BlueSMiRF. Once the bluetooth passes the character to the Arduino, you could use a condition statement to reset the Arduino. A brief search online, I came across this Arduino forum post that might be of some use => [https://forum.arduino.cc/index.php?topic=381083.msg2629005#msg2629005](https://forum.arduino.cc/index.php?topic=381083.msg2629005#msg2629005). 

Otherwise, you can post in the [Arduino](https://forum.arduino.cc/) or [SFE Forums](https://forum.sparkfun.com/) for further assistance.
